# =============================================================================
# pnpm Workspaces Configuration
# =============================================================================
# Definiuje pnpm workspace dla monorepo
# =============================================================================

packages:
  # Aplikacje
  - 'apps/*'
  
  # Pakiety współdzielone
  - 'packages/*'
