/**
 * PDF Generator Utilities
 *
 * Client-side PDF generation for colouring pages
 * Uses pdf-lib for PDF creation
 */

import { PDFDocument, rgb } from 'pdf-lib';

// Trusted domains for image URLs
const TRUSTED_DOMAINS = [
  'localhost',
  'r2.dev', // Cloudflare R2
];

/**
 * Validate image URL - must be from trusted domain
 */
export function isImageUrlTrusted(url: string): boolean {
  try {
    const parsedUrl = new URL(url);
    const hostname = parsedUrl.hostname;

    return TRUSTED_DOMAINS.some((domain) => hostname.endsWith(domain) || hostname === domain);
  } catch {
    return false;
  }
}

/**
 * Fetch image as Uint8Array
 */
async function fetchImageAsBytes(url: string): Promise<Uint8Array> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to fetch image: ${response.status}`);
  }
  const arrayBuffer = await response.arrayBuffer();
  return new Uint8Array(arrayBuffer);
}

/**
 * Generate PDF with coloring page image
 * Creates A4 page with the image centered
 */
export async function generatePdf(
  title: string,
  description: string,
  imageUrl?: string
): Promise<Uint8Array> {
  // Create PDF document (A4 size: 595 x 842 points)
  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595, 842]);

  // A4 dimensions
  const pageWidth = 595;
  const pageHeight = 842;
  const margin = 20;

  // If we have an image URL, embed it
  if (imageUrl) {
    try {
      const imageBytes = await fetchImageAsBytes(imageUrl);
      
      // Try to detect image type and embed accordingly
      let image;
      try {
        // Try embedding as PNG first
        image = await pdfDoc.embedPng(imageBytes);
      } catch {
        try {
          // Fall back to JPEG
          image = await pdfDoc.embedJpg(imageBytes);
        } catch {
          // If both fail, skip the image
          console.warn('Could not embed image, skipping');
          image = null;
        }
      }

      if (image) {
        // Calculate dimensions to fit the page while maintaining aspect ratio
        const imageWidth = image.width;
        const imageHeight = image.height;
        
        // Available space for image (with margins)
        const maxWidth = pageWidth - (margin * 2);
        const maxHeight = pageHeight - (margin * 2);

        // Calculate scale to fit
        const scaleX = maxWidth / imageWidth;
        const scaleY = maxHeight / imageHeight;
        const scale = Math.min(scaleX, scaleY, 1); // Don't upscale

        const scaledWidth = imageWidth * scale;
        const scaledHeight = imageHeight * scale;

        // Center the image on the page
        const imageX = (pageWidth - scaledWidth) / 2;
        const imageY = (pageHeight - scaledHeight) / 2;

        // Draw the image
        page.drawImage(image, {
          x: imageX,
          y: imageY,
          width: scaledWidth,
          height: scaledHeight,
        });

        // Add title at the top
        page.drawText(title, {
          x: margin,
          y: pageHeight - margin - 20,
          size: 16,
          color: rgb(0, 0, 0),
        });

        return pdfDoc.save();
      }
    } catch (error) {
      console.warn('Failed to embed image in PDF:', error);
      // Continue without image if embedding fails
    }
  }

  // Fallback: simple PDF without image or if image fails
  page.drawText(title, {
    x: margin,
    y: pageHeight - margin - 20,
    size: 24,
    color: rgb(0, 0, 0),
  });

  // Add description
  page.drawText(description, {
    x: margin,
    y: pageHeight - margin - 50,
    size: 14,
    color: rgb(0.4, 0.4, 0.4),
  });

  // Add placeholder text if no image
  if (!imageUrl) {
    page.drawText('[Kolorowanka do wydrukowania]', {
      x: margin,
      y: pageHeight / 2,
      size: 12,
      color: rgb(0.6, 0.6, 0.6),
    });
  }

  // Add footer
  page.drawText('Generated by colouring-Pages', {
    x: margin,
    y: margin,
    size: 10,
    color: rgb(0.8, 0.8, 0.8),
  });

  return pdfDoc.save();
}

/**
 * Download PDF as a blob and trigger download in browser
 */
export function downloadPdf(pdfBytes: Uint8Array, filename: string): void {
  const blob = new Blob([new Uint8Array(pdfBytes)], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  URL.revokeObjectURL(url);
}

/**
 * Generate and download PDF in one call
 */
export async function generateAndDownloadPdf(
  title: string,
  description: string,
  imageUrl?: string
): Promise<void> {
  const pdfBytes = await generatePdf(title, description, imageUrl);
  const filename = `${title.toLowerCase().replace(/\s+/g, '-')}.pdf`;
  downloadPdf(pdfBytes, filename);
}
