/**
 * PDF Generator Utilities
 *
 * Client-side PDF generation for colouring pages
 * Uses pdf-lib for PDF creation
 */

import { PDFDocument, rgb } from 'pdf-lib';

// Trusted domains for image URLs
const TRUSTED_DOMAINS = [
  'localhost',
  'r2.dev', // Cloudflare R2
];

/**
 * Validate image URL - must be from trusted domain
 */
export function isImageUrlTrusted(url: string): boolean {
  try {
    const parsedUrl = new URL(url);
    const hostname = parsedUrl.hostname;

    return TRUSTED_DOMAINS.some((domain) => hostname.endsWith(domain) || hostname === domain);
  } catch {
    return false;
  }
}

/**
 * Generate a simple PDF with a colouring page placeholder
 *
 * In MVP, this creates a simple PDF with the page title
 * Later, this will embed the actual colouring page image
 */
export async function generatePdf(
  title: string,
  description: string,
  imageUrl?: string
): Promise<Uint8Array> {
  // Create PDF document
  const pdfDoc = await PDFDocument.create();

  // Add page (A4 size: 595 x 842 points)
  const page = pdfDoc.addPage([595, 842]);

  // Add title
  page.drawText(title, {
    x: 50,
    y: 750,
    size: 24,
    color: rgb(0, 0, 0),
  });

  // Add description
  page.drawText(description, {
    x: 50,
    y: 700,
    size: 14,
    color: rgb(0.4, 0.4, 0.4),
  });

  // Add placeholder for image
  if (imageUrl) {
    // For now, just add a note that image would go here
    page.drawText('[Image placeholder: ' + imageUrl + ']', {
      x: 50,
      y: 500,
      size: 12,
      color: rgb(0.6, 0.6, 0.6),
    });
  }

  // Add footer
  page.drawText('Generated by colouring-Pages', {
    x: 50,
    y: 50,
    size: 10,
    color: rgb(0.8, 0.8, 0.8),
  });

  // Return PDF as bytes
  return pdfDoc.save();
}

/**
 * Download PDF as a blob and trigger download in browser
 */
export function downloadPdf(pdfBytes: Uint8Array, filename: string): void {
  // Create blob from PDF bytes - convert to regular array to avoid type issues
  const blob = new Blob([new Uint8Array(pdfBytes)], { type: 'application/pdf' });
  const url = URL.createObjectURL(blob);

  const link = document.createElement('a');
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);

  // Clean up
  URL.revokeObjectURL(url);
}

/**
 * Generate and download PDF in one call
 */
export async function generateAndDownloadPdf(
  title: string,
  description: string,
  imageUrl?: string
): Promise<void> {
  const pdfBytes = await generatePdf(title, description, imageUrl);
  const filename = `${title.toLowerCase().replace(/\s+/g, '-')}.pdf`;
  downloadPdf(pdfBytes, filename);
}
